manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    -name: zmk-hid-io
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-hid-io
      remote: badjeff
      revision: main
  self:
    path: config
